title: "Fluente-Mente"

description: >
  Impara l'inglese in modo pratico, semplice e sostenibile.

url: "https://nausica-20.github.io"

baseurl: "/Fluente-Mente"

lang: "it"

timezone: "Europe/Rome"

author:
  name: "Fluente-Mente"


# Permalink degli articoli
permalink: /:categories/:title/


# Markdown
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false


# Plugin essenziali
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap


# Esclusioni
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor


# Feed
feed:
  path: feed.xml
