# =========================================================
# FLUENTE-MENTE
# Jekyll Configuration
# =========================================================

title: "Fluente-Mente"

description: >
  Inglese pratico, inglese reale e metodi semplici
  per imparare e usare l'inglese nella vita quotidiana.

lang: "it"

url: "https://nausica-20.github.io"
baseurl: "/FluenteMente"

author:
  name: "Fluente-Mente"

github_username: "Nausica-20"


# =========================================================
# BUILD
# =========================================================

markdown: kramdown

timezone: Europe/Rome

permalink: pretty


# =========================================================
# PLUGINS
# =========================================================

  plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# =========================================================
# DEFAULTS
# =========================================================

defaults:

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "it"

  - scope:
      path: ""
    values:
      layout: "default"
      lang: "it"


# =========================================================
# EXCLUDE
# =========================================================

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
  - prompts
  - output
