#!/usr/bin/env python3
"""
Fluente-Mente Content Writer Engine v1.0

Purpose:
- Read production packets created by the Article Production Engine.
- Generate a complete Markdown article draft using a deterministic structure.
- Preserve the canonical front matter contract.
- Never invent unsupported learning targets or commercial claims.
- Never mark the article as publish-ready.

Important:
This engine is a writing framework. For high-quality language content, the actual
English examples/dialogues should be supplied or generated by an approved LLM
according to the prompt contract, then passed through QA.
"""

from pathlib import Path
import argparse
import re
import yaml

ARTICLE_STATUS = "drafting"

def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}

def fm_value(v):
    return v if v not in (None, "") else "CONFIGURE"

def quote_yaml(v):
    return yaml.safe_dump(v, allow_unicode=True, default_flow_style=False).strip()

def build_front_matter(fm):
    lines = ["---"]
    ordered = [
        "content_id","title","slug","description","date","last_modified","author","language",
        "domain","cluster","topic","content_type","parent_content","related_content",
        "learning_path","level","skill","user_job","learning_outcome",
        "search_intent","primary_keyword","secondary_keywords","canonical",
        "meta_title","meta_description","primary_language_focus",
        "target_expressions","target_words","grammar_focus",
        "natural_english","textbook_vs_natural","real_life_context",
        "funnel_role","commercial_intent","babbel_relevance","primary_cta",
        "recommended_next_content","recommended_path","recommended_cluster",
        "pinterest_intent","pinterest_angle","pin_count",
        "priority","status","evergreen","update_frequency","original_content",
        "featured_image","og_image","index","follow","sitemap"
    ]
    present = {k:v for k,v in fm.items() if v is not None}
    for k in ordered:
        if k in present:
            v = present[k]
            if isinstance(v, (dict, list)):
                block = yaml.safe_dump({k:v}, allow_unicode=True, sort_keys=False).rstrip()
                lines.extend(block.splitlines())
            elif isinstance(v, bool):
                lines.append(f"{k}: {'true' if v else 'false'}")
            else:
                sval = str(v).replace('"', '\\"')
                lines.append(f'{k}: "{sval}"')
    for k,v in present.items():
        if k not in ordered:
            if isinstance(v, (dict, list)):
                lines.extend(yaml.safe_dump({k:v}, allow_unicode=True, sort_keys=False).rstrip().splitlines())
            else:
                lines.append(f'{k}: "{str(v).replace(chr(34), chr(92)+chr(34))}"')
    lines.append("---")
    return "\n".join(lines)

def exprs(brief, bucket):
    lt = brief.get("language_targets", {}) or {}
    ex = lt.get("expressions", {}) or lt.get("target_expressions", {}) or {}
    vals = ex.get(bucket, []) if isinstance(ex, dict) else []
    return vals or []

def words(brief, bucket):
    lt = brief.get("language_targets", {}) or {}
    wd = lt.get("words", {}) or lt.get("target_words", {}) or {}
    vals = wd.get(bucket, []) if isinstance(wd, dict) else []
    return vals or []

def make_language_box(brief):
    core_e = exprs(brief, "core")
    sup_e = exprs(brief, "supporting")
    core_w = words(brief, "core")
    sup_w = words(brief, "supporting")
    out = ["## Le espressioni da portare via", ""]
    if core_e:
        out += ["**Core language**", ""]
        for x in core_e:
            out.append(f"- **{x}**")
        out.append("")
    if sup_e:
        out += ["**Supporting language**", ""]
        for x in sup_e:
            out.append(f"- {x}")
        out.append("")
    if core_w or sup_w:
        out += ["### Le parole utili", ""]
        for x in core_w:
            out.append(f"- **{x}**")
        for x in sup_w:
            out.append(f"- {x}")
        out.append("")
    return "\n".join(out)

def build_article(packet, render_stub=True):
    fm = packet["front_matter_contract"].copy()
    brief = packet["article_blueprint"]["brief"]
    fm["status"] = ARTICLE_STATUS

    title = fm_value(fm.get("title"))
    outcome = fm_value(fm.get("learning_outcome"))
    user_job = fm_value(fm.get("user_job"))
    primary = fm_value(fm.get("primary_keyword"))

    parts = [build_front_matter(fm), ""]
    parts += [
        f"# {title}",
        "",
        f"> **Obiettivo:** {outcome}",
        "",
        f"Se stai cercando di **{user_job}**, questa guida parte da una situazione reale "
        f"e ti mostra come usare l'inglese in modo più naturale.",
        "",
        "## Perché questa situazione può essere difficile",
        "",
        "Qui va spiegato in modo concreto il problema comunicativo dell'utente, "
        "senza trasformare l'articolo in una lezione scolastica.",
        "",
        "## La soluzione in inglese naturale",
        "",
        "Qui va presentata la strategia comunicativa principale del learning brief.",
        ""
    ]

    # Language target box
    parts.append(make_language_box(brief))

    parts += [
        "## Come si usa davvero",
        "",
        "Inserire qui esempi brevi e contestualizzati, privilegiando frasi naturali "
        "e spiegazioni in italiano.",
        "",
        "### Esempio",
        "",
        "> **English:** [MODEL SENTENCE FROM LEARNING BRIEF]",
        "",
        "Spiegazione in italiano: perché questa formulazione è naturale e quando usarla.",
        "",
        "## Attenzione a questo errore",
        "",
        "Quando previsto dal brief, mostrare il contrasto tra una formulazione "
        "letterale o scolastica e una formulazione naturale.",
        "",
        "### Da evitare",
        "",
        "> [TEXTBOOK / LITERAL VERSION]",
        "",
        "### Più naturale",
        "",
        "> [NATURAL VERSION]",
        "",
        "## Prova a usarlo",
        "",
        "Inserire una micro-attività guidata coerente con il livello: completamento, "
        "trasformazione, scelta della formula migliore o mini-risposta personale.",
        "",
        "## In sintesi",
        "",
        "- Una cosa da ricordare.",
        "- Una formula da riutilizzare.",
        "- Un contesto reale in cui provarla.",
        "",
        "## Continua il percorso",
        "",
        "Collegare qui il contenuto successivo o il learning path indicato nel packet.",
        "",
        "[CTA_PRIMARY]",
        "",
        "> **Nota:** il contenuto è indipendente da Babbel. Eventuali link affiliati "
        "devono seguire la disclosure e le regole definite in `affiliate.yml`.",
        ""
    ]

    return "\n".join(parts)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--packets", default="_articles/generated")
    ap.add_argument("--out", default="_articles/drafts")
    ap.add_argument("--content-id", default=None)
    args = ap.parse_args()

    root = Path(args.root)
    pdir = root / args.packets
    out = root / args.out
    out.mkdir(parents=True, exist_ok=True)

    packet_files = sorted(pdir.glob("*.yml"))
    packet_files = [p for p in packet_files if p.name != "PRODUCTION_REPORT.yml"]
    if args.content_id:
        packet_files = [p for p in packet_files if p.stem == args.content_id]

    errors = []
    written = 0

    for p in packet_files:
        packet = load_yaml(p)
        cid = packet.get("content_id")
        if not cid:
            errors.append(f"{p.name}: missing content_id")
            continue
        if packet.get("status") != "production_ready":
            errors.append(f"{p.name}: packet is not production_ready")
            continue
        try:
            article = build_article(packet)
            target = out / f"article-{cid.lower()}.md"
            target.write_text(article, encoding="utf-8")
            written += 1
        except Exception as e:
            errors.append(f"{p.name}: {e}")

    report = {"written": written, "errors": errors, "status": "ok" if not errors else "failed"}
    (out / "WRITER_REPORT.yml").write_text(
        yaml.safe_dump(report, allow_unicode=True, sort_keys=False),
        encoding="utf-8"
    )
    print(yaml.safe_dump(report, allow_unicode=True, sort_keys=False))
    raise SystemExit(0 if not errors else 1)

if __name__ == "__main__":
    main()
